### ISSUE TITLE
Endpoint for setting the default page

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#499] opened 2018-02-16 14:23 UTC
It would be very helpful if you could set the default page of a resource over plone.restapi.

**Comment by tisto** [comment] 2018-06-19 10:59
@zopyx we are still trying to make the folderish approach work. I wouldn't mind adding a default page setting. Though this is not a top priority for us right now.

**Comment by tisto** [comment] 2018-06-19 11:11
Duplicate of #411

**Closed by tisto** 2018-06-19 11:11 UTC
Labels: 04 type: enhancement, 14 prio: low
