### ISSUE TITLE
Provide endpoint to inspect schema of User type

### ISSUE THREAD

**Issue by fulv** [plone/plone.restapi#413] opened 2017-10-22 08:48 UTC
The `@users` endpoint already provides most facilities needed to manage users.  However, when the user schema has been customized (e.g. via `http://localhost:8080/Plone/@@member-fields`), there is no way currently for a client of the restapi to discover this.  Thus, it is not possible to automatically generate the required form based on the custom schema of the user type.

What would be needed is something akin to `@types/User`, with the same functionality that the `@types` endpoint provides for all "normal" content types.  However, I'm not sure if we should actually extend the `@types` endpoint for this (`@types/User` would break if an actual `User` dexterity content type were to be created), or the `@users` endpoint.

**Comment by tisto** [comment] 2017-10-25 16:06
I guess the @types endpoint could provide a json schema with the user schema. Or we could use the expansion mechanism to embed the json schema information in the user response. If anybody is willing to work on this I'd be happy to help/review.

**Comment by fulv** [comment] 2017-10-25 17:07
I would lean towards the expansion mechanism for the user response, mostly because I can't imagine how the `@types` endpoint could be called for the user schema.

**Comment by sneridagh** [comment] 2018-01-18 10:11
+1 on this.

**Comment by davisagli** [comment] 2022-09-04 04:39
duplicate of #706

**Closed by davisagli** 2022-09-04 04:39 UTC
Labels: 04 type: enhancement
