### ISSUE TITLE
@types on Plone 5.0.6rc1 (5016) generates errors

### ISSUE THREAD

**Issue by sk-rest** [plone/plone.restapi#190] opened 2017-02-01 12:51 UTC
Fetching all types via @types/<type> generates errors:

```
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types HTTP/1.1" 200 1200 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Image HTTP/1.1" 500 267 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/File HTTP/1.1" 500 267 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Collection HTTP/1.1" 500 267 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Discussion Item HTTP/1.1" 500 274 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/LIF HTTP/1.1" 200 47500 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/LRF HTTP/1.1" 200 47493 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Link HTTP/1.1" 200 48774 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/News Item HTTP/1.1" 500 267 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Folder HTTP/1.1" 200 61476 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Document HTTP/1.1" 200 61523 "" "lwp/0.1 libwww-perl/6.08"
127.0.0.1 - Anonymous [01/Feb/2017:13:48:49 +0200] "GET /Plone/@types/Event HTTP/1.1" 500 371 "" "lwp/0.1 libwww-perl/6.08"
```

Note, there are some 500 responses without detailed error below:

```
2017-02-01T13:23:23 ERROR Zope.SiteErrorLog 1485951803.390.727467254795 http://localhost:8080/Plone/@types/Image
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 20, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.types.get, line 50, in reply
  Module plone.restapi.types.utils, line 134, in get_jsonschema_for_portal_type
  Module plone.restapi.types.utils, line 115, in get_jsonschema_for_fti
  Module plone.restapi.types.adapters, line 73, in get_schema
  Module plone.restapi.types.adapters, line 279, in additional
  Module plone.restapi.types.adapters, line 275, in get_properties
  Module plone.restapi.types.utils, line 96, in get_fields_from_schema
  Module plone.restapi.types.adapters, line 61, in get_schema
  Module plone.restapi.types.adapters, line 77, in get_type
NotImplementedError
------
2017-02-01T13:23:23 ERROR Zope.SiteErrorLog 1485951803.440.90387285714 http://localhost:8080/Plone/@types/Discussion%20Item
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 20, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.types.get, line 50, in reply
  Module plone.restapi.types.utils, line 134, in get_jsonschema_for_portal_type
  Module plone.restapi.types.utils, line 108, in get_jsonschema_for_fti
  Module plone.restapi.types.utils, line 37, in get_ordered_fields
AttributeError: lookupSchema
------
2017-02-01T13:23:24 ERROR Zope.SiteErrorLog 1485951804.150.634276138722 http://localhost:8080/Plone/@types/Event
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 20, in __call__
  Module plone.restapi.services, line 22, in render
  Module json, line 250, in dumps
  Module json.encoder, line 209, in encode
  Module json.encoder, line 434, in _iterencode
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 442, in _iterencode
  Module json.encoder, line 184, in default
TypeError: datetime.datetime(2017, 2, 1, 14, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>) is not JSON serializable

```

**Comment by tisto** [comment] 2017-02-17 11:06
@sk-rest I do not see any 5.0.6rc1 release: http://dist.plone.org/release/

This wouldn't really make sense since we already had a final 5.0.x release a long time ago. Can you please double-check?

**Comment by tisto** [comment] 2017-02-27 12:17
I can not reproduce the error and @sk-rest does not reply. Will close the issue for now. Feel free to re-open with more details.

**Closed by tisto** 2017-02-27 12:17 UTC
Labels: 01 type: bug
