### ISSUE TITLE
Tiles / Mosaic

### ISSUE THREAD

**Issue by robgietema** [plone/plone.restapi#350] opened 2017-05-03 14:39 UTC
To get mosaic working with plone-react and the restapi we will need some endpoints, here's a list:

# Available tiles

`/plone/@tiles`

Should list all available tiles including metadata:

```
[
  {
    "@id": "http://localhost:55001/plone/@tiles/sample.tile", 
    "title": "A title for the tile",
    "description": "My tile's description",
  }, 
]
```

The tile endpoint (`/@tiles/sample.tile`) should return the schema of the tile similar to the `/@types/Document` endpoint.

# Page Layouts

These are all the page layouts available for different contenttypes. They are called content layouts in Plone now. Both names are confusing to me since they are not really layouts but rather templates for the content so maybe it's better to call them templates.

`/plone/@templates`

Should list all the available templates including metadata and the template itself. Currently the templates are html based but this should be json based since the new mosaic editor is using json.

```
[
  {
    "@id": "http://localhost:55001/plone/@templates/basic",
    "title": "Basic",
    "description": "Some basic description",
    "types": ["Document", "Event"],
    "panels": {
      "content": {
        "rows": [
          {
            "columns": [
              {
                "width": 12,
                "tiles": [
                  {
                    "type": "field",
                    "field": "title"
                  },
                  {
                    "type": "field",
                    "field": "description"
                  },
                  {
                    "type": "sample.tile",
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
]
```

Patch and post calls are also nice to have to update and create new templates.

# Site Layouts

Currently the site layouts are stored / registered in Plone including all the html markup. I think registering the available site layouts with a name and description should be enough since all the layouts will be created in the frontend packages. And since page layouts are renamed to templates just layouts will do as an identifier here.

`/plone/@layouts`

Should list all the available layouts.

```
[
  {
    "@id": "http://localhost:55001/plone/@templates/basic",
    "title": "Basic",
    "description": "Some basic description",
  }
]
```

# Fetching / storing content

The content endpoints should be extended to contain the mosaic data.

`/plone/folder/my-document`

Should return panel data:

```
{
  "@id": "http://localhost:55001/plone/folder/my-document",
  ...
  "panels": {
    "content": {
      "rows": [
        {
          "columns": [
            {
              "width": 12,
              "tiles": [
                {
                  "type": "field",
                  "field": "title"
                },
                {
                  "type": "field",
                  "field": "description"
                },
                {
                  "type": "sample.tile",
                  "data": {
                    "some_schema_field": "My string",
                    "some_other_field": 42
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

# Settings layouts

We can reuse the current layout field on the content objects.

# Additions to the types endpoint
- add `available_templates` to the `/@types/<type>` endpoint
- add `default_template` to the `/@types/<type>` endpoint

# Extra's

If we want to replace portlet functionality also we should be able to inherit panel data. This means a child page should receive the tiles from the parent for a specific panel if it is not overwritten. The frontend should know wether or not the panel contains tiles stored on the child itself or are inherited. This can be done with an `inherited` boolean field for each panel.

**Comment by robgietema** [comment] 2017-05-03 14:41
@tisto @datakurre feedback is welcome!

**Comment by datakurre** [comment] 2017-05-03 14:58
@robgietema This looks good for me. @tisto maybe this should be assigned to me? I cannot work on this right now, but Rob told he should have some more time for plone-react in June and I could implement this before that.

**Comment by tomgross** [comment] 2017-05-03 18:05
This is a duplicate of #203 but since this is more actively discussed I'll close #203.

**Comment by tisto** [comment] 2017-05-03 19:32
@robgietema awesome! thank you! Looks good to me overall. I would re-use the expansion mechanism that we are about to merge in the next versions of plone.restapi:

https://github.com/plone/plone.restapi/blob/414bdb0c2e86aa0ba2e195674d8bb5023b4980ec/docs/source/expansion.rst

Therefore "/plone/folder/my-document?expand=mosaic" would look something like:

```
{
  "@id": "http://localhost:55001/plone/folder/my-document",
  ...
  "@components": {
    "mosaic": {
      "@id": "http://localhost:55001/plone/folder/my-document/@mosaic",
      "panels": {
        "content": {
          "rows": []
        }
      ]
    }
  }
}
```

We would basically just implement a context-specific "@mosaic" endpoint that exposes the mosaic layout for that specific content object:

http://localhost:55001/plone/folder/my-document/@mosaic

The expansion mechanism would allow embedding this into the content GET.

It might be easier for us to discuss those issues if we would create a pull request with a mosaic.rst document in the docs/source folder. I really like the docs first approach, especially for API discussions. Once we have a final spec anybody who has time could start to implement this endpoint. And you could adapt your front end implementation to that spec even before it is implemented. ;)

**Comment by davisagli** [comment] 2017-05-03 19:35
Does this implementation belong in plone.restapi or plone.app.mosaic or some other package?

**Comment by datakurre** [comment] 2017-05-03 19:41
I believe most of the dependencies (if not all) required for these end points are in plone.app.tiles and plone.app.blocks and plone.app.mosaic may not be needed. So, I would prefer Rob's naming recommendation (tiles, templates, layouts and panels instead of mosaic). I believe this could be in plone.restapi and be active when plone.app.blocks is available. (If some requirement still remains in plone.app.mosaic, it could be moved into plone.app.blocks.)

**Comment by tisto** [comment] 2017-05-03 19:44
@davisagli good point. So far plone.restapi is just a wrapper around plone core functionality. A plone.app.mosaic package would need to depend on plone.restapi (and not only plone.rest) because of the expansion mechanism. We could, of course, create an adaptation mechanism that allows plug-ins to hook into the expansion. Not sure if that is worth the effort though. I put quite a lot of effort into creating something similar for plone.app.discussion and eight years later, nobody has ever used it. :)

**Comment by tisto** [comment] 2017-05-03 19:46
@datakurre @robgietema please excuse my ignorance of the mosaic naming conventions. Feel free to choose whatever naming you find appropriate. I was just trying to make a point about the expansion. :)

**Comment by datakurre** [comment] 2017-05-03 20:13
@tisto Not so fast about p.a.discussion. I'm currently extending it with audio support for our client :)

**Comment by sunew** [comment] 2017-11-23 22:21
@tisto a little off topic, but I have done some initial work on serializing portlets - I'm not sure if it would belong in plone.restapi or in a separate module - what do you think?

**Comment by tisto** [comment] 2017-11-24 08:17
@sunew I guess both would be fine with me. plone.restapi could support portlets as an expandable component or we could create a separate add-on product for it. Actually, our team (at kitconcept) is currently discussing if we want to use portlets or tiles for the "edit sidebar" use case. cc @robgietema @sneridagh 

In the past we used a documentation-first approach for plone.restapi enhancements that worked pretty well. Could you image to write a short rst document describing how your portlet rest api would work?

**Comment by tisto** [comment] 2017-11-24 08:19
@sunew FYI: I created a new issue to discuss portlets support for plone.restapi to keep this separate from tiles: 

https://github.com/plone/plone.restapi/issues/445

**Comment by tisto** [comment] 2019-06-15 09:25
Done.

**Closed by tisto** 2019-06-15 09:25 UTC
Labels: 04 type: enhancement
