### ISSUE TITLE
Image scaling issues not handled properly: AttributeError: 'NoneType' object has no attribute 'url' in plone.restapi.imaging

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#642] opened 2018-11-20 12:17 UTC
The following error is being raised in plone.restapi 3.2.1 with an image that displays properly in Plone 4.3 but has possibly some issues with Pillow...the error indicates that the error handling or error checking could be improved here for providing a better error message on the API level

```
2018-11-20 13:09:29 ERROR plone.namedfile.scaling Could not scale "<plone.namedfile.file.NamedBlobImage object at 0x7facc6934668>" of <bound method Image.absolute_url of <Image at /scale/de/unternehmen/unternehmen/gruppenfoto_2018.png>>
Traceback (most recent call last):
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/plone.namedfile-4.2.5-py2.7.egg/plone/namedfile/scaling.py", line 253, in __call__
    **parameters
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/plone.namedfile-4.2.5-py2.7.egg/plone/namedfile/scaling.py", line 200, in create_scale
    **parameters
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/plone.scale-3.0.2-py2.7.egg/plone/scale/scale.py", line 55, in scaleImage
    image = PIL.Image.open(image)
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/Pillow-5.2.0-py2.7-linux-x86_64.egg/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
IOError: cannot identify image file <open file '/tmp/BUC9YaJlq', mode 'rb' at 0x7facc4eabeb0>
2018-11-20 13:09:32 ERROR Zope.SiteErrorLog 1542715769.960.0462378598138 http://localhost:5080/scale/de/unternehmen/unternehmen/POST_application_json_
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.content.add, line 99, in reply
  Module plone.restapi.serializer.dxcontent, line 84, in __call__
  Module plone.restapi.serializer.dxfields, line 48, in __call__
  Module plone.restapi.imaging, line 54, in get_original_image_url
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by davisagli** [comment] 2018-11-20 12:31
Duplicate of #637

**Closed by davisagli** 2018-11-20 12:31 UTC
