### ISSUE TITLE
Upgrade Step Evolution Error: Version 

### ISSUE THREAD

**Issue by cintiacinquini** [plone/plone.restapi#465] opened 2017-12-19 13:59 UTC
We have a project called Identidade de Governo (IDG) https://github.com/plonegovbr/brasil.gov.portal whose version was updated from 1.4 to 1.5. 
_plone.restapi_ was incorporated in version 1.5 (https://github.com/plonegovbr/portal.buildout/blob/2e0a598f4e330fd6ebb43d815d5b1e4d7ea82a4c/buildout.d/versions.cfg#L106) which was not present in the previous version, 1.4. 
We have a portal in production with real contents. During the Upgrade Steps from 1.4 to 1.5 in this portal, we ran into this error message:

> Traceback (innermost last):
> Module ZPublisher.Publish, line 138, in publish
> Module ZPublisher.mapply, line 77, in mapply
> Module ZPublisher.Publish, line 48, in call_object
> Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
> Module Products.GenericSetup.upgrade, line 166, in doStep
> Module brasil.gov.portal.upgrades.v10803, line 21, in install_restapi
> Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 602, in installProduct
> __traceback_info__: ('plone.restapi',)
> Module Products.GenericSetup.tool, line 388, in runAllImportStepsFromProfile
> __traceback_info__: profile-plone.restapi:default
> Module Products.GenericSetup.tool, line 1433, in _runImportStepsFromContext
> Module Products.GenericSetup.tool, line 1245, in _doRunImportStep
> __traceback_info__: plone.restapi
> Module plone.restapi.setuphandlers, line 32, in import_various
> Module plone.restapi.setuphandlers, line 12, in install_pas_plugin
> AttributeError: __contains__
![relatorio de upgrade steps do portal federativo-1_html_6d69e603](https://user-images.githubusercontent.com/2236313/34160289-70f37018-e4b3-11e7-831c-b9f8720bef01.png)

**Comment by tisto** [comment] 2017-12-20 18:33
@buchi any idea what could cause this?

**Comment by tisto** [comment] 2018-06-19 11:08
Closing this issue because we were never able to reproduce it. Feel free to re-open if you disagree.

**Comment by hvelarde** [comment] 2018-09-12 14:30
I just stumbled with this issue; I'm going to recommend not to install plone.restapi until https://github.com/plone/plone.rest/issues/73 is fixed.

**Comment by tisto** [comment] 2018-09-12 19:43
@hvelarde your comment seems to be unrelated to the issue. Do you disagree with closing this one?

**Comment by lukasgraf** [comment] 2018-09-12 20:15
The referenced issue (plonegovbr/brasil.gov.portal#525) does indeed look like the same problem - I think the issue about the `Vary` header in `plone.rest` might have been linked by mistake.

The exception `AttributeError: __contains__` happens on the last line of this bit:

```python
def install_pas_plugin(context):
    uf_parent = aq_inner(context)
    while True:
        uf = getToolByName(uf_parent, 'acl_users')
        if 'jwt_auth' not in uf:
```

The only way I can see `uf` not having a `__contains__` method in this situation is if it's not actually a user folder (a `PluggableAuthService` object, which gets its `__contains__` method by inheriting from `OFS.ObjectManager.ObjectManager`).

@hvelarde could you check what kind of object `uf` is in your case when this upgrade step is run? It should be an instance of [`PluggableAuthService`](https://github.com/zopefoundation/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/PluggableAuthService.py#L174`), but it seems to be something else in your case.

**Comment by hvelarde** [comment] 2018-09-12 22:04
bingo! the Plone site is inside a folder!

![selection_023](https://user-images.githubusercontent.com/341393/45455786-aac6d900-b6be-11e8-9112-bfc6afea5cd1.png)

**Comment by lukasgraf** [comment] 2018-09-13 11:34
@hvelarde I tested locally with a Plone site inside a folder - that works for me, so I can't reproduce the issue. So the fact that the Plone site is in a folder might be related, but not sufficient to cause the issue.

It would be helpful to know what type of object `uf` is in your case.

Also, I noticed that since the error also happens on line `12` in your case, you must be using a pretty old version of `plone.restapi` (ca. Dec 2017). The code in that setuphandler has changed slightly over time, so not sure if the problem is still present in the most recent version.

Can I assign this issue to you for further debugging, since you currently seem to be the only one able to reproduce it?

**Comment by hvelarde** [comment] 2018-09-13 13:17
seems `acl_users` is being acquired by acquisition from the Zope root:

```pypdb
AttributeError: __contains__
> /opt/plone/buildout/eggs/plone.restapi-1.0a23-py2.7.egg/plone/restapi/setuphandlers.py(12)install_pas_plugin()
-> if 'jwt_auth' not in uf:
(Pdb) uf
<UserFolder at /acl_users used for /brazilgovnews>
(Pdb) 'jwt_auth' not in uf
*** AttributeError: __contains__
(Pdb) uf.objectIds()
()
```
that folder only has the **admin** user inside.

let me know if I can help you further.

**Comment by lukasgraf** [comment] 2018-09-13 14:09
Ah, I see now - your `uf` is actually a `UserFolder` instance. I tested a Plone Site within a Folder locally, but I *didn't* check the `[ ] Create user folder` checkbox when creating the folder. That's what's making the difference I think.

However, walking up to the Zope Application root (not just the Plone site) is very much intentional - the `jwt` PAS Plugin also needs to be installed to the Zope App root, otherwise authenticating with users from that userfolder won't work (this was added in #412).

I think we should therefore just skip the special `UserFolder` when walking up the acquisition chain. I'll review your PR shortly and provide some more specific feedback.

**Closed** 2018-09-13 19:28 UTC
Labels: 01 type: bug
