### ISSUE TITLE
Why does @types require authentication?

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi#321] opened 2017-04-19 16:42 UTC
Are we sure we want that?

I can imagine cases where we need to load a schema in order to render a content (not necessarily to modify it).
We also have cases where anonymous users have Contributors privileges (so schema has to be loaded at some point).

**Comment by davisagli** [comment] 2022-12-08 17:18
Closing as a duplicate of #1409 which has more discussion.

**Closed by davisagli** 2022-12-08 17:18 UTC
