### ISSUE TITLE
Incorrect Json examples in plone restapi documentation

### ISSUE THREAD

**Issue by envy7** [plone/plone.restapi#273] opened 2017-03-17 20:02 UTC
I saw a lot of json examples with an extra **comma** in the end in the plone restapi documentation

![issue1](https://cloud.githubusercontent.com/assets/12188993/24060690/63e3078e-0b7a-11e7-89a4-049d26ad774c.png)
![issue2](https://cloud.githubusercontent.com/assets/12188993/24060691/63f5f1e6-0b7a-11e7-8696-6e9199d9b3d6.png)
![issue3](https://cloud.githubusercontent.com/assets/12188993/24060692/63f80a1c-0b7a-11e7-9350-1aa45a89e544.png)
![issue4](https://cloud.githubusercontent.com/assets/12188993/24060693/64396d9a-0b7a-11e7-9250-68cb6f0268cc.png)

**Comment by tisto** [comment] 2017-03-18 06:44
@envy7 thanks for reporting! We started to move all examples in the docs to use @datakurre's fabulous https://pypi.python.org/pypi/sphinxcontrib-httpexample. I suspect that the extra comma comes from old, not-yet-migrated examples. Could you image to help with replacing the old examples with the new ones?

**Comment by datakurre** [comment] 2017-03-18 08:09
Yes. Those all are old examples - yet to be migrated (and fixed).

**Comment by envy7** [comment] 2017-03-18 08:27
@tisto I would love to help but I really don't know how to begin, if you could shed some light on how I have to go about it, I'll find all the examples such as this and replace them with the new ones

**Comment by datakurre** [comment] 2017-03-18 08:48
Fixing the examples require that you are able to run plone.restapi tests. There's a special test suite https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/tests/test_documentation.py which does functional testing for the documented API and then exports request and response into files. Then those request and response are linked into documentation (there's a lot of examples). After this, the call examples are generated by documentation build.

**Comment by envy7** [comment] 2017-03-18 09:58
@datakurre Okay I thought I just had to edit https://github.com/plone/plone.restapi/docs/source/content.rst and remove the commas, I'm still new to plone :sweat_smile: so by testing you mean running unit tests like the ones mentioned here https://docs.plone.org/develop/testing/unit_testing.html#running-unit-tests where I use

    bin/test -s package.subpackage -t !test_name

**Comment by datakurre** [comment] 2017-03-18 10:52
Yes. Examples are generated by testing to ensure that they are valid. The original issue you reported was AFAIK caused by those examples still being written manually (and prone to human errors) directly into the docs :)

**Comment by envy7** [comment] 2017-03-18 12:46
So, I executed

    bin/test -s  plone.restapi --list-tests

I got a number of tests that are related to documentation, the ones mentioned in test_documentation.py i.e

    test_documentation_404_not_found
    test_documentation_batching
    test_documentation_breadcrumbs...

Now Do I have to execute these one by one i.e

    bin/test -s  plone.restapi -t test_documentation_batching

Am I on the right track? this will automatically generate the correct json?

**Comment by lukasgraf** [comment] 2017-03-18 12:56
@envy7 this (or `bin/test -t test_documentation` for short) will correctly *update* the JSON examples.

But for the examples you mentioned, the "tests" that produce them mainly need to be *written first* (in `test_documentation.py`), because they don't exist yet.

I already started with that on the way back from the sprint, but didn't create a PR yet because those changes would conflict with everyone else's open PRs. So idea was to wait until the major open PRs were merged, and then get those documentation fixes in all at once, in one big sweep and in a short time windows, to avoid stepping on everybody's toes.

Will do a PR next week to migrate the existing examples, and maybe add some meta-docs on how to work with them.

**Comment by envy7** [comment] 2017-03-18 13:02
@lukasgraf ok sure, I not experienced in python myself :sweat_smile: thanks a lot.

**Comment by lukasgraf** [comment] 2017-03-18 13:04
@envy7 no worries - this isn't even something Python or Plone specific, it's a totally custom mechanism for `plone.restapi` 😉

**Comment by tisto** [comment] 2017-03-22 11:22
@envy7 closing this issue since it should have been solved by now. Feel free to re-open if this shouldn't be the case.

**Closed by tisto** 2017-03-22 11:22 UTC
Labels: 01 type: bug
