### ISSUE TITLE
Write on Read (GET request)

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#867] opened 2020-02-19 05:37 UTC
## Environment

- Plone 5.2.1
- Plone REST API 6.2.2
- Volto 4.0.0-alpha.37

## Problem

- We see lots of writes on GET requests, you can see this in "Undo" tab of the ZMI:

<img width="915" alt="Screenshot 2020-02-19 at 06 18 17" src="https://user-images.githubusercontent.com/632105/74804195-cd134c00-52df-11ea-97eb-eb4460d70cef.png">

## Possible Reason

We saw massive scalability issues in our pre-production site. The site has lots of image content and uses several (70) Volto composite pages with up to 30-50 images that all requires individual requests.

We could mitigate the problem for now by:

- reducing the number of requests in Volto (fixes went upstream)
- using caching as much as possible (Varnish)
- using a warm-up script that crawls the image-heavy composite pages
- tweaking the prod configuration

We also asked @jensens for help with Plone backend optimizations (e.g. https://github.com/zopefoundation/zope.interface/pull/156), which drastically improved things.

It seems the reason for those writes is that plone.scaling creates the image scales on read, in order to save disk/db space. I haven't confirmed this and we haven't looked into this yet though.

**Comment by mauritsvanrees** [comment] 2022-09-29 21:26
Recent `plone.namedfile` versions in Plone 6 support requesting scales with `pre=True`. This "pre-registers" the scale on a unique url, without actually scaling it with Pillow. The `portal_catalog` has an `image_scales` metadata which uses this, and it pre-registers all scales for the image. This happens when saving the image, so on a write.

So if the image scales were indeed the problem, this should be fixed now. I will close. Please reopen if you still see this with latest Plone 6 beta 2.

**Closed by mauritsvanrees** 2022-09-29 21:26 UTC
Labels: 01 type: bug, 04 type: enhancement, 12 prio: high, 43 lvl: complex

**Comment by davisagli** [comment] 2022-09-29 23:42
@mauritsvanrees There will still be a write on read when the image scale is downloaded, if it hasn't been generated yet. But, I think that is working as designed. It's good that generating the scales is deferred (because some scales might not be used), it's good that generating it is no longer required just to link to it, it's good that when it is generated it is only one scale at a time (so the transaction is shorter and has less chance of conflicting), and it's good that when the transactions show up in the undo log now it will show the path to the image itself rather than the page that references it. Maybe we still need to revisit it, but it seems we are making progress.
